### PR TITLE
fix field reference usage and fix specs

### PR DESCRIPTION
**Pull request by colinsurprenant**
- fix Event field references
- fix specs that relied on private implementation
- a bit of cleanups

relates to elastic/logstash#4264 and elastic/logstash#4191

### CODE REVIEW

**Comment by colinsurprenant** [comment]
@guyboertje friendly review ping!

**Comment by guyboertje** [comment]
This all looks good but I can't help wondering if the code would benefit from a Visitor style treatment to have the different UA fields added by classes that know better what to do.

Maybe a different PR.

Otherwise LGTM.

**Comment by colinsurprenant** [comment]
@guyboertje thanks. I guess we could but given the very straightforward nature of this codebase I think pragmatically this is probably the most efficient way of doing it, for me adding a visitor style pattern, while cleaner, you lean toward over engineering...

**Comment by colinsurprenant** [comment]
merged, bumped & pushed version 2.0.4

**Pull request merged**
