### PR TITLE
Ability to replace source with target

### PR DESCRIPTION
**Pull request by efouts**
e.g.

```
filter {
  useragent {
    source => "useragent"
    target => "useragent"
  }
}
```

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot for your contribution @efouts, speaking about this change do you have a particular use case of this? I mean i kinda see the benefit, but would like to know your experience with it.

Thanks a lot,

- purbon

**Comment by purbon** [comment]
On the other side, it would be nice if you can update also the changelog and the plugin version as you introduce new functionality. 

Thanks

**Comment by efouts** [comment]
In my experience, I wanted a single field to represent this data in the end. So id prefer to not have to remove an old field once this filter created the new one. I can see how some may want to retain the original string and in that case id provide another pull request after this one to preserve the original string as a subfield, [target][string].

Ill go ahead and add the changelog and version.

**Comment by jordansissel** [comment]
Code LGTM. Idea LGTM. 

Let's get the changelog addition done and we can probably merge :)

**Comment by efouts** [comment]
Updated version and add the changelog entry.

**Pull request closed without merging**
