### PR TITLE
Handling simple OS name.

### PR DESCRIPTION
**Pull request by athoune**
Provides naive os name family for easy grouping.

### CODE REVIEW

**Comment by changa** [comment]
This would be a nice addition! :+1:

**Comment by efouts** [comment]
This introduces a new responsibility of parsing for this filter. It seems like it would be more at home as a change to https://github.com/ua-parser/uap-core/blob/master/regexes.yaml.

**Comment by jordansissel** [comment]
@efouts I agree, but I'm open for having this patch in the useragent filter until this is shipped upstream into the ua-parser core.

**Comment by jordansissel** [comment]
jenkins, test it

**Comment by athoune** [comment]
Rebase is to hard, see https://github.com/logstash-plugins/logstash-filter-useragent/pull/19

**Pull request closed without merging**
