### PR TITLE
Remove vendor stuff since uap gem already has .yaml file

### LINKED ISSUE #7: plugin never uses vendor/regexes.yaml since uap gem already includes it
```
% find . -name regexes.yaml
./vendor/bundle/jruby/1.9/gems/logstash-filter-useragent-1.0.1/vendor/regexes.yaml
./vendor/bundle/jruby/1.9/gems/user_agent_parser-2.2.0/vendor/ua-parser/regexes.yaml
```

Deleting the first yaml file doesn't stop it from working, only deleting the second one, included in the ua-parser gem.

It seems the first file is only loaded if [UserAgentParser::Parser.new raises an exception](https://github.com/logstash-plugins/logstash-filter-useragent/blob/master/lib/logstash/filters/useragent.rb#L42-L47), which doesn't happen

### PR DESCRIPTION
**Pull request by jsvd**
the current plugin includes a yaml file that is never used so this pr removes it

closes #7

### CODE REVIEW

**Comment by jordansissel** [comment]
LGTM, but I haven't tested.

**Comment by efouts** [comment]
This would probably close #9 in the since it would be out of scope of this project, passing the buck onto [uap-ruby](https://github.com/ua-parser/uap-ruby/issues/20).

**Comment by talevy** [comment]
Looks like this needs a rebase

**Comment by original-brownbear** [comment]
@jsvd this I automatically did in #38 now :)

**Pull request closed without merging**
