### PR TITLE
 #45 ensure thread safety on user agent parsing

### LINKED ISSUE #45: StringIndexOutOfBoundsException: Uknown error while parsing user agent data
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: Upgraded from logstash 5.4.0 to 5.4.2
- Operating System: CentOS 7
- Config File (if you have sensitive info, please remove it):
```
...
			useragent { 
				add_tag => [ "UA" ] 
				prefix => "ua_"
				source => "message" 
			} 

...
```

- Sample Data:
```
[2017-06-26T11:22:37,901][ERROR][logstash.filters.useragent] Uknown error while parsing user agent data {:exception=>java.lang.StringIndexOutOfBoundsException: String index out of range: 283, :field=>"message", :event=>2017-06-26T09:21:03.000Z zawww03 40.77.167.124 www.bidorbuy.co.za - 2017-06-26 11:21:03 "GET /item/184465577/Pet_SMALL_Mystery_Box_a_Lucky_Packet_for_Your_Beloved_Pet_WoW_Surprise_for_Dogs_and_Cats.html HTTP/1.1" 410 66162 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" deflate: - pct.}
[2017-06-26T11:22:38,374][ERROR][logstash.filters.useragent] Uknown error while parsing user agent data {:exception=>java.lang.StringIndexOutOfBoundsException: String index out of range: 267, :field=>"message", :event=>2017-06-26T09:21:03.000Z zawww03 169.159.129.48 www.bidorbuy.co.za - 2017-06-26 11:21:03 "GET /images/ui/bobe.sprites_user_c289f58b47e3641dbefb660a24904dc3.png HTTP/1.1" 200 49472 "http://www.bidorbuy.co.za/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0" deflate: - pct.}

```

Worked fine before upgrade.

### PR DESCRIPTION
**Pull request by original-brownbear**
Fixes #45 

* `java.util.regex.Matcher` aren't threadsafe, fixed (and reproduced with the new test) by `synchronize`ing the 3 individual methods that use them and the LRU map (which could throw NPE on concurrent access otherwise :(). Everything else doesn't need sync, so I figured this should be a fine approach since we're probably not going to see all that much contention here.
   * I could see a more sophisticated approach here using thread-locals for the matcher and concurrent hash map, but I was working from the assumption that the additional cost in memory that would bring may be more optimally used for a larger cache (this could be wrong, but is fairly hard to benchmark, this change should have no change in memory use characteristics and only a minor performance hit CPU wise)

### CODE REVIEW

**Comment by original-brownbear** [comment]
@suyograo in case you find a second, maybe don't forget about this one :) Another report in #47

**Comment by AntonioMeireles** [comment]
hey... @elastic ppl - any ETA for this being merged... ? Thanks in advance!

**Comment by original-brownbear** [comment]
@suyograo ping for when you're available again :)

**Comment by original-brownbear** [comment]
@jsvd thanks! Merging + publishing then :)

**Pull request closed without merging**
